### ISSUE TITLE
別講義の課題が投げられてしまっている？

### ISSUE THREAD

**Issue by youjo-tape** [wakita/y18-prg1#1]
ocw-i にて、Coding Assignment 1 として Functional Programming なる講義の課題が設定されてしまっているように思われます（課題ページ：https://wakita.github.io/fp2018/page/assignment1.html）

**Comment by wakita** [comment]
失礼いたしました！大学院で教えている Functional Programming という授業の課題を過って送ってしまいました。無視して下さい。

**Comment by wakita** [comment]
過って設定した課題は削除しました。お騒がせしました。
