### ISSUE TITLE
講義資料 day03.pdf のビット演算の具体例が誤っている

### ISSUE THREAD

**Issue by youjo-tape** [wakita/y18-prg1#3]
day03.pdf 28 ページの計算例：
3 ^ 5 = 0011(2) ^ 0101(2) = 0111(2) = 7
~5 = ~0101(2) = 1010(2) = 12
は、正しくは
3 ^ 5 = 0011(2) ^ 0101(2) = 0110(2) = 6
~5 = ~0101(2) = 1010(2) = 10
ではないでしょうか

**Comment by wakita** [comment]
確認しました。おっしゃるとおりです。

修正版をプッシュしました。

38d2d61d755a832876a107ccad0f64ee3b2fd4f6
